version: 2.1

# Define executors to reuse configuration across jobs
executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo



jobs:
  build:
    executor: python-executor
    steps:
      - run:
          name: Run practice.py
          command: |
            . venv/bin/activate
            python practice.py

workflows:
  build_and_test:
    jobs:
      - build
